# Generated by Django 5.2.4 on 2025-08-29 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0004_delete_code_alter_user_is_del'),
        ('code_dict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('is_del', models.IntegerField(blank=True, db_column='del', db_comment='逻辑删除，0启用，1停用', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_comment='创建时间', null=True)),
                ('create_user', models.BigIntegerField(blank=True, db_comment='创建用户', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
                ('update_user', models.BigIntegerField(blank=True, db_comment='更新用户', null=True)),
                ('id', models.BigIntegerField(db_comment='智能体ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='智能体名称', max_length=255)),
                ('description', models.TextField(db_comment='智能体描述')),
                ('avatar', models.CharField(blank=True, db_comment='智能体图标存储地址', max_length=255, null=True)),
                ('baseurl', models.CharField(db_comment='智能体API请求地址', max_length=255)),
                ('apikey', models.CharField(db_comment='智能体api请求的认证key', max_length=255)),
                ('usage_count', models.IntegerField(db_comment='智能体使用用户数', default=0)),
                ('agent_type', models.IntegerField(choices=[(0, '共同使用'), (1, '老师专用'), (2, '学生专用')], db_comment='智能体类型', default=0)),
            ],
            options={
                'db_table': 'tb_agent',
                'db_table_comment': '智能体表',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='AgentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.IntegerField(blank=True, db_column='del', db_comment='逻辑删除，0启用，1停用', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_comment='创建时间', null=True)),
                ('create_user', models.BigIntegerField(blank=True, db_comment='创建用户', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
                ('update_user', models.BigIntegerField(blank=True, db_comment='更新用户', null=True)),
                ('agent', models.ForeignKey(db_comment='智能体ID', on_delete=django.db.models.deletion.RESTRICT, to='agent.agent')),
                ('tag', models.ForeignKey(db_comment='标签ID', on_delete=django.db.models.deletion.RESTRICT, to='code_dict.code')),
            ],
            options={
                'db_table': 'tb_agent_tag',
                'db_table_comment': '智能体标签关联表',
                'unique_together': {('agent', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='tags',
            field=models.ManyToManyField(related_name='agents', through='agent.AgentTag', to='code_dict.code'),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.IntegerField(blank=True, db_column='del', db_comment='逻辑删除，0启用，1停用', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_comment='创建时间', null=True)),
                ('create_user', models.BigIntegerField(blank=True, db_comment='创建用户', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
                ('update_user', models.BigIntegerField(blank=True, db_comment='更新用户', null=True)),
                ('title', models.CharField(db_comment='对话标题', max_length=255)),
                ('conversation_id', models.CharField(blank=True, db_comment='Dify会话ID', max_length=255, null=True, unique=True)),
                ('agent', models.ForeignKey(db_comment='所属智能体', on_delete=django.db.models.deletion.RESTRICT, to='agent.agent')),
                ('user', models.ForeignKey(db_comment='所属用户', on_delete=django.db.models.deletion.RESTRICT, to='auth.user')),
            ],
            options={
                'db_table': 'conversation',
                'db_table_comment': '对话会话表',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.IntegerField(blank=True, db_column='del', db_comment='逻辑删除，0启用，1停用', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_comment='创建时间', null=True)),
                ('create_user', models.BigIntegerField(blank=True, db_comment='创建用户', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
                ('update_user', models.BigIntegerField(blank=True, db_comment='更新用户', null=True)),
                ('content', models.TextField(db_comment='消息内容')),
                ('role', models.CharField(db_comment='角色：user-用户，assistant-AI助手', max_length=255)),
                ('related_questions', models.JSONField(blank=True, db_comment='相关推荐问题', null=True)),
                ('metadata', models.JSONField(blank=True, db_comment='消息元数据', null=True)),
                ('message_id', models.CharField(db_comment='Dify消息ID', max_length=255)),
                ('conversation', models.ForeignKey(db_comment='所属对话', on_delete=django.db.models.deletion.CASCADE, to='agent.conversation')),
            ],
            options={
                'db_table': 'message',
                'db_table_comment': '对话消息表',
                'ordering': ['-create_time'],
            },
        ),
    ]
