# Generated by Django 5.2.4 on 2025-09-15 15:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(blank=True, db_comment='Dify对话ID', default=uuid.uuid4, null=True),
        ),
    ]
