# Generated by Django 5.2.4 on 2025-09-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.IntegerField(blank=True, db_column='del', db_comment='逻辑删除，0启用，1停用', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_comment='创建时间', null=True)),
                ('create_user', models.BigIntegerField(blank=True, db_comment='创建用户', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
                ('update_user', models.BigIntegerField(blank=True, db_comment='更新用户', null=True)),
                ('school_name', models.CharField(blank=True, db_comment='学校名称', max_length=255, null=True)),
                ('school_id_code', models.CharField(blank=True, db_comment='学校标识码', max_length=255, null=True)),
                ('authorities', models.CharField(blank=True, db_comment='主管部门', max_length=255, null=True)),
                ('location', models.CharField(blank=True, db_comment='所在地', max_length=255, null=True)),
                ('edu_level', models.IntegerField(blank=True, choices=[(0, '专科'), (1, '本科')], db_comment='办学层次，0-专科，1-本科', null=True)),
                ('remarks', models.CharField(blank=True, db_comment='备注', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_university',
                'db_table_comment': '高校信息表',
            },
        ),
    ]
