# Generated by Django 5.2.4 on 2025-09-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='edu_level',
            field=models.CharField(blank=True, db_comment='办学层次', max_length=255, null=True),
        ),
    ]
