# Generated by Django 5.2.4 on 2025-09-02 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_teacher_user_id_teacher_user'),
        ('university', '0002_alter_university_edu_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='stu_friendly_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(blank=True, db_comment='出生日期', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (0, '女')], db_comment='性别', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='professional_title',
            field=models.IntegerField(blank=True, db_comment='职称，具体以码表为准', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.IntegerField(blank=True, db_comment='学科，具体以码表为准', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='university',
            field=models.ForeignKey(blank=True, db_comment='学校', null=True, on_delete=django.db.models.deletion.RESTRICT, to='university.university'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profession',
            field=models.IntegerField(blank=True, db_comment='职务, 如教师、教授等，具体以码表为准', null=True),
        ),
    ]
