# Generated by Django 5.2.4 on 2025-08-17 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='permission',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', db_comment='父级权限', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='permission.permission'),
        ),
    ]
